[project]
name = "tasks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.7",
    "langchain-ollama>=1.0.0",
    "langgraph>=1.0.3",
    "pydantic>=2.12.4",
    "rich>=14.2.0",
    "typing>=3.10.0.0",
]
